# Generated by Django 5.2.4 on 2025-08-03 14:14

from django.db import migrations

def create_default_currency_and_assign_to_products(apps, schema_editor):
    """Crea la moneda por defecto y la asigna a productos existentes"""
    Currency = apps.get_model('store', 'Currency')
    Product = apps.get_model('store', 'Product')
    
    # Crear moneda por defecto (CUP)
    default_currency, created = Currency.objects.get_or_create(
        code='CUP',
        defaults={
            'name': 'Peso Cubano',
            'symbol': '₱',
            'exchange_rate': 1.0000,
            'is_active': True,
            'is_default': True
        }
    )
    
    # Asignar la moneda por defecto a todos los productos existentes
    Product.objects.filter(currency__isnull=True).update(currency=default_currency)

def reverse_func(apps, schema_editor):
    """Función de reversión (no hace nada en este caso)"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_currency_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_currency_and_assign_to_products, reverse_func),
    ]
