# Generated by Django 5.2.4 on 2025-08-03 14:19

from django.db import migrations, models
import django.db.models.deletion

def make_currency_required(apps, schema_editor):
    """Hace el campo currency obligatorio"""
    Product = apps.get_model('store', 'Product')
    Currency = apps.get_model('store', 'Currency')
    
    # Obtener la moneda por defecto
    default_currency = Currency.objects.filter(is_default=True).first()
    if not default_currency:
        default_currency = Currency.objects.first()
    
    # Asignar moneda por defecto a productos sin moneda
    if default_currency:
        Product.objects.filter(currency__isnull=True).update(currency=default_currency)

def reverse_func(apps, schema_editor):
    """Función de reversión (no hace nada)"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20250803_1414'),
    ]

    operations = [
        migrations.RunPython(make_currency_required, reverse_func),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='store.currency',
                verbose_name='Moneda'
            ),
        ),
    ]
