# Generated by Django 5.2.4 on 2025-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250803_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Recoger en Tienda'), ('delivery', 'Mensajería')], default='pickup', max_length=20, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de WhatsApp'),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Enviado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Dirección de Envío'),
        ),
    ]
